// <auto-generated />
namespace Vinay.Time.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddedRegHours : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedRegHours));
        
        string IMigrationMetadata.Id
        {
            get { return "201405121117432_AddedRegHours"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
