// <auto-generated />
namespace eClock.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Added_FKRelations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_FKRelations));
        
        string IMigrationMetadata.Id
        {
            get { return "201405031233427_Added_FKRelations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
